name: CI

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]
  workflow_dispatch:

# jobs:
#   mac:
#     name: macOS
#     runs-on: macOS-13
#     steps:
#     - uses: actions/checkout@v3
#     - name: Start Postgres
#       run: brew services start postgresql
#     - name: Select Xcode 14.0.1
#       run: sudo xcode-select -s /Applications/Xcode_14.0.1.app
#     - name: Bootstrap
#       run: make bootstrap
#     - name: Run tests
#       run: make test

#   ubuntu:
#     name: Ubuntu
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: 'sudo apt-get --fix-missing update && sudo apt-get install -y wamerican'
#     - name: Bootstrap
#       run: make bootstrap-client
#     - name: Run tests
#       run: make test-server-linux

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: xcodebuild
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: DevelopersButler.xcodeproj
          scheme: DevelopersButler
          destination: platform=macOS
          action: build
