name: CI

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build: 
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps: 
    - name: Checkout project repo
      uses: actions/checkout@v3
      
    - name: Build
      shell: bash
      run: xcodebuild -scheme DevelopersButler build

  test: 
    runs-on: macos-latest
    timeout-minutes: 30

    steps: 
    - name: Checkout project repo
      uses: actions/checkout@v3
      
    - name: Test
      shell: bash
      run: xcodebuild -scheme DevelopersButler test
